version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 80:80
    networks:
      - mynetwork
    volumes:
      - static:/usr/share/nginx/html
    links:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: sumair
      MYSQL_PASSWORD: password
    networks:
      - mynetwork
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  mynetwork:
    driver: bridge
volumes:
  static:
  mysql-data:
